/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RemoteRouteImport } from './routes/remote'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LocalSessionRouteImport } from './routes/local-session'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionIdRouteImport } from './routes/session.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RemoteRoute = RemoteRouteImport.update({
  id: '/remote',
  path: '/remote',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalSessionRoute = LocalSessionRouteImport.update({
  id: '/local-session',
  path: '/local-session',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionIdRoute = SessionIdRouteImport.update({
  id: '/session/$id',
  path: '/session/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/local-session': typeof LocalSessionRoute
  '/profile': typeof ProfileRoute
  '/remote': typeof RemoteRoute
  '/settings': typeof SettingsRoute
  '/session/$id': typeof SessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/local-session': typeof LocalSessionRoute
  '/profile': typeof ProfileRoute
  '/remote': typeof RemoteRoute
  '/settings': typeof SettingsRoute
  '/session/$id': typeof SessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/local-session': typeof LocalSessionRoute
  '/profile': typeof ProfileRoute
  '/remote': typeof RemoteRoute
  '/settings': typeof SettingsRoute
  '/session/$id': typeof SessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/history'
    | '/home'
    | '/local-session'
    | '/profile'
    | '/remote'
    | '/settings'
    | '/session/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/history'
    | '/home'
    | '/local-session'
    | '/profile'
    | '/remote'
    | '/settings'
    | '/session/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/history'
    | '/home'
    | '/local-session'
    | '/profile'
    | '/remote'
    | '/settings'
    | '/session/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  HistoryRoute: typeof HistoryRoute
  HomeRoute: typeof HomeRoute
  LocalSessionRoute: typeof LocalSessionRoute
  ProfileRoute: typeof ProfileRoute
  RemoteRoute: typeof RemoteRoute
  SettingsRoute: typeof SettingsRoute
  SessionIdRoute: typeof SessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remote': {
      id: '/remote'
      path: '/remote'
      fullPath: '/remote'
      preLoaderRoute: typeof RemoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local-session': {
      id: '/local-session'
      path: '/local-session'
      fullPath: '/local-session'
      preLoaderRoute: typeof LocalSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$id': {
      id: '/session/$id'
      path: '/session/$id'
      fullPath: '/session/$id'
      preLoaderRoute: typeof SessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  HistoryRoute: HistoryRoute,
  HomeRoute: HomeRoute,
  LocalSessionRoute: LocalSessionRoute,
  ProfileRoute: ProfileRoute,
  RemoteRoute: RemoteRoute,
  SettingsRoute: SettingsRoute,
  SessionIdRoute: SessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
