/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LocalSessionRouteImport } from './routes/local-session'
import { Route as LiveRouteImport } from './routes/live'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ExtensionRouteImport } from './routes/extension'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as RecordRouteImport } from './routes/Record'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecordIndexRouteImport } from './routes/record/index'
import { Route as SessionIdRouteImport } from './routes/session.$id'
import { Route as RecordTypeRouteImport } from './routes/record.$type'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalSessionRoute = LocalSessionRouteImport.update({
  id: '/local-session',
  path: '/local-session',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionRoute = ExtensionRouteImport.update({
  id: '/extension',
  path: '/extension',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordRoute = RecordRouteImport.update({
  id: '/Record',
  path: '/Record',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordIndexRoute = RecordIndexRouteImport.update({
  id: '/record/',
  path: '/record/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionIdRoute = SessionIdRouteImport.update({
  id: '/session/$id',
  path: '/session/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordTypeRoute = RecordTypeRouteImport.update({
  id: '/record/$type',
  path: '/record/$type',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Record': typeof RecordRoute
  '/auth': typeof AuthRoute
  '/extension': typeof ExtensionRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/live': typeof LiveRoute
  '/local-session': typeof LocalSessionRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/record/$type': typeof RecordTypeRoute
  '/session/$id': typeof SessionIdRoute
  '/record/': typeof RecordIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Record': typeof RecordRoute
  '/auth': typeof AuthRoute
  '/extension': typeof ExtensionRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/live': typeof LiveRoute
  '/local-session': typeof LocalSessionRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/record/$type': typeof RecordTypeRoute
  '/session/$id': typeof SessionIdRoute
  '/record': typeof RecordIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Record': typeof RecordRoute
  '/auth': typeof AuthRoute
  '/extension': typeof ExtensionRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/live': typeof LiveRoute
  '/local-session': typeof LocalSessionRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/record/$type': typeof RecordTypeRoute
  '/session/$id': typeof SessionIdRoute
  '/record/': typeof RecordIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Record'
    | '/auth'
    | '/extension'
    | '/history'
    | '/home'
    | '/live'
    | '/local-session'
    | '/profile'
    | '/settings'
    | '/record/$type'
    | '/session/$id'
    | '/record/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Record'
    | '/auth'
    | '/extension'
    | '/history'
    | '/home'
    | '/live'
    | '/local-session'
    | '/profile'
    | '/settings'
    | '/record/$type'
    | '/session/$id'
    | '/record'
  id:
    | '__root__'
    | '/'
    | '/Record'
    | '/auth'
    | '/extension'
    | '/history'
    | '/home'
    | '/live'
    | '/local-session'
    | '/profile'
    | '/settings'
    | '/record/$type'
    | '/session/$id'
    | '/record/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RecordRoute: typeof RecordRoute
  AuthRoute: typeof AuthRoute
  ExtensionRoute: typeof ExtensionRoute
  HistoryRoute: typeof HistoryRoute
  HomeRoute: typeof HomeRoute
  LiveRoute: typeof LiveRoute
  LocalSessionRoute: typeof LocalSessionRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  RecordTypeRoute: typeof RecordTypeRoute
  SessionIdRoute: typeof SessionIdRoute
  RecordIndexRoute: typeof RecordIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local-session': {
      id: '/local-session'
      path: '/local-session'
      fullPath: '/local-session'
      preLoaderRoute: typeof LocalSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extension': {
      id: '/extension'
      path: '/extension'
      fullPath: '/extension'
      preLoaderRoute: typeof ExtensionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Record': {
      id: '/Record'
      path: '/Record'
      fullPath: '/Record'
      preLoaderRoute: typeof RecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/record/': {
      id: '/record/'
      path: '/record'
      fullPath: '/record/'
      preLoaderRoute: typeof RecordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$id': {
      id: '/session/$id'
      path: '/session/$id'
      fullPath: '/session/$id'
      preLoaderRoute: typeof SessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/record/$type': {
      id: '/record/$type'
      path: '/record/$type'
      fullPath: '/record/$type'
      preLoaderRoute: typeof RecordTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RecordRoute: RecordRoute,
  AuthRoute: AuthRoute,
  ExtensionRoute: ExtensionRoute,
  HistoryRoute: HistoryRoute,
  HomeRoute: HomeRoute,
  LiveRoute: LiveRoute,
  LocalSessionRoute: LocalSessionRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  RecordTypeRoute: RecordTypeRoute,
  SessionIdRoute: SessionIdRoute,
  RecordIndexRoute: RecordIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
